# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: pagure-exporter.spec

# add or remove files that should be synced
files_to_sync:
    - pagure-exporter.spec
    - .packit.yaml

jobs:
- job: copr_build
  trigger: pull_request
  targets:
    - fedora-rawhide
    - fedora-40


# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: pagure-exporter
# downstream (Fedora) RPM package name
downstream_package_name: pagure-exporter
